modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/GillesSchippers/Vampirism-Expanded/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/GillesSchippers/Vampirism-Expanded"
logoFile = "assets/expanded/icon.png"
updateJSONURL = "https://neoforge.curseupdate.com/1522717/expanded"
credits = "Maran124, QDuif"
authors = "Gilles Schippers"
description = '''
An exciting expansion to the Vampirism mod that introduces new mechanics, features, and a deeper gameplay experience for players.
'''
[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "vampirism"
type = "required"
versionRange = "${vampirism_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "guideapi_vp"
type = "optional"
versionRange = "${guideapi_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "bloodlines"
type = "optional"
versionRange = "${bloodlines_version_range}"
ordering = "AFTER"
side = "BOTH"